// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGA0aGsViwTdBeO5PjT2668gi5dz8t-Wg',
    appId: '1:1043757695386:web:e921fbb78c1bbb92ce7a23',
    messagingSenderId: '1043757695386',
    projectId: 'chatapp-be9e2',
    authDomain: 'chatapp-be9e2.firebaseapp.com',
    storageBucket: 'chatapp-be9e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPPsfIEU7OaPTZ9P942GxYYUAwTLz1-8',
    appId: '1:1043757695386:android:e8f07c7423f62589ce7a23',
    messagingSenderId: '1043757695386',
    projectId: 'chatapp-be9e2',
    storageBucket: 'chatapp-be9e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddlauw6gkIu6rFfl1Z2WpBEJcm07BThM',
    appId: '1:1043757695386:ios:061b0379c56f7a67ce7a23',
    messagingSenderId: '1043757695386',
    projectId: 'chatapp-be9e2',
    storageBucket: 'chatapp-be9e2.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddlauw6gkIu6rFfl1Z2WpBEJcm07BThM',
    appId: '1:1043757695386:ios:f5df3da22705d1d3ce7a23',
    messagingSenderId: '1043757695386',
    projectId: 'chatapp-be9e2',
    storageBucket: 'chatapp-be9e2.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
